### ISSUE TITLE
Program Manager knows too much

### ISSUE THREAD

**Issue by Maikon** [Katerina-codes/data_searching#15]
If you look at the first method of `ProgramManager` it's clear what its concerned with. The below two methods seem out of place and are dealing with details the `ProgramManager` should not know. This means this class now has _low cohesion_ since it has multiple reasons to change and which are not related (i.e splitting records on a new line, reading from a file etc).

Consider extracting the below methods to other object(s).

https://github.com/Katerina-codes/data_searching/blob/edc950fb8afebf9b14ec26de88be04ec0a0deb33/lib/program_manager.rb#L16-L27

**Comment by Katerina-codes** [comment]
Fixed.
