### ISSUE TITLE
Top down reading/writing of code

### ISSUE THREAD

**Issue by Maikon** [Katerina-codes/data_searching#3]
`get_valid_input` is using `is_input_valid?` which is defined above it. If method A is using method B, method B should be defined below method A. A more general way of thinking about it is high level ideas are placed at the top whilst lower level details are placed in the bottom.

https://github.com/Katerina-codes/data_searching/blob/fc7fdcd94794d3efd878cff60f07e6052d966be8/lib/ui.rb#L28-L37

**Comment by Katerina-codes** [comment]
Resolved.

**Comment by Maikon** [comment]
👍 Make sure to close the issue if it is resolved. Alternatively, merging a PR that is linked to this issue, automatically closes the issue.
